name: Analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo docker run --rm -v $PWD/:/data/project/ jetbrains/qodana-jvm-community:2021.2 --show-report
