name: Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew build
      - uses: JetBrains/qodana-action@v3.1.1
        id: qodana
        with:
          linter: qodana-jvm-community
          fail-threshold: 1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: ${{ github.workspace }}/qodana
      - name: Print problems
        if: always()
        run: cat qodana/report/results/result-allProblems.json | jq
      - name: SARIF Annotator
        if: always()
        uses: SirYwell/sarif-annotator@v0.2.1
        with:
          source: qodana
          report-path: ${{ steps.qodana.outputs.results-json-path }}
