name: Build Docker image
on:
  push:
    branches:
      - master

env:
  JAVA_VERSION: 17

jobs:
  docker:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up JDK
        uses: "actions/setup-java@v1"
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Docker meta
        id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@v1"
        with:
          images: "ghcr.io/${{ github.repository }}"
          tag-sha: true
          tag-custom: latest

      - name: "Unfuck fucked up build script"
        run: |
          rm build
          sed -i 's/buildDir = File("_build")/buildDir = File("build")/g' build.gradle.kts

      - name: "Login to ghcr.io"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        env:
          IMAGE_TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: ./gradlew jib
