name: mjtest

on:
  push:
    branches: [ master ]
  pull_request:

env:
  JAVA_VERSION: 17

jobs:
  mjtest-tests-tests:
    name: "Run basic mjtest-tests tests"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "./mjtest/mjt.py lexer syntax ast semantic ./run"

  mjtest-firm:
    name: "Run firm compile"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "./mjtest/mjt.py compile-firm ./run"

  mjtest-djungelskog:
    name: "Run Djungelskog compile"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "./mjtest/mjt.py compile ./run"

  mjtest-molki:
    name: "Run molki compile"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git clone --recursive https://github.com/Firmwehr/molki /tmp/molki"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: sed -i 's/"$@"/--molki-binary \/tmp\/molki\/molki.py --compile-molki "${@:2}"/' run
      - run: "./mjtest/mjt.py compile-firm ./run"
