name: mjtest

on:
  push:
    branches: [ master ]
  pull_request:

env:
  JAVA_VERSION: 17

jobs:
  common:
    name: "Test common functionality"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "rm -r mjtest/tests/exec/big/"
      - run: "rm mjtest/tests/exec/Vector.java"
      - run: "./mjtest/mjt.py lexer syntax ast semantic ./run"

  firm:
    name: "Test firm"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "rm -r mjtest/tests/exec/big/"
      - run: "rm mjtest/tests/exec/Vector.java"
      - run: "./mjtest/mjt.py compile-firm compile-firm-only ./run"

  firm-opt:
    name: "Test firm with optimizations"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "rm -r mjtest/tests/exec/big/"
      - run: "rm mjtest/tests/exec/Vector.java"
      - run: "rm mjtest/tests/exec/Calculator.*"
      - run: "./mjtest/mjt.py compile-firm compile-firm-only ./run_opt"

  ikea:
    name: "Test ikea"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "rm -r mjtest/tests/exec/big/"
      - run: "rm mjtest/tests/exec/Vector.java"
      - run: "./mjtest/mjt.py compile compile-only ./run"

  ikea-opt:
    name: "Test ikea with optimizations"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/checkout@v2
      - name: Build using build script
        run: ./build
      - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
      - run: "git -C mjtest/tests reset --hard origin/master"
      - run: "rm -r mjtest/tests/exec/big/"
      - run: "rm mjtest/tests/exec/Vector.java"
      - run: "./mjtest/mjt.py compile compile-only ./run_opt"

  # lego:
  #   name: "Test lego"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: ${{ env.JAVA_VERSION }}
  #     - uses: actions/checkout@v2
  #     - name: Build using build script
  #       run: ./build
  #     - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
  #     - run: "git -C mjtest/tests reset --hard origin/master"
  #     - run: "rm -r mjtest/tests/exec/big/"
  #     - run: "rm mjtest/tests/exec/Vector.java"
  #     - run: "./mjtest/mjt.py compile compile-only ./run_lego"

  # lego-opt:
  #   name: "Test lego with optimizations"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: ${{ env.JAVA_VERSION }}
  #     - uses: actions/checkout@v2
  #     - name: Build using build script
  #       run: ./build
  #     - run: "git clone --recursive https://git.scc.kit.edu/IPDSnelting/mjtest mjtest"
  #     - run: "git -C mjtest/tests reset --hard origin/master"
  #     - run: "rm -r mjtest/tests/exec/big/"
  #     - run: "rm mjtest/tests/exec/Vector.java"
  #     - run: "./mjtest/mjt.py compile compile-only ./run_lego_opt"
